CC  = gcc
CFLAGS  = -g
RM  = rm -f

 
default:    all

all:    c
 
c:   
	mkdir -p bin
	${CC} ${CFLAGS} src/HomeWork0MarkTikhonov.c -o bin/HomeWork0MarkTikhonov

s:
	bin/HomeWork0MarkTikhonov

# clean veryclean:    $(RM) main